### ISSUE TITLE
Enabling 'follow_set_cookies' with no set-cookie header

### ISSUE THREAD

**Issue by rc0x03** [tomas/needle#121]
Having `follow_set_cookies` enabled while requesting a page that doesn't send a `set-cookie` header will cause needle to crash.

```javascript
/root/node-osmosis/node_modules/needle/lib/cookies.js:72
  res = Object.keys(obj).map(function(key) {
               ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.exports.write (/root/node-osmosis/node_modules/needle/lib/cookies.js:72:16)
    at ClientRequest.<anonymous> (/root/node-osmosis/node_modules/needle/lib/needle.js:401:46)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1692:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1587:20)
    at TCP.onread (net.js:527:27)
```

Seems like either `cookies.read` needs to always return an object or `cookies.write` needs to check that `obj` isn't undefined.

**Comment by tomas** [comment]
Good find. Will check tomorrow as part of #111 (which I meant to merge today, haha).
