### ISSUE TITLE
test cases are failing on master

### ISSUE THREAD

**Issue by knksmith57** [tomas/needle#168]
Heya, looks like tests are failing on master:

```
❯ jq '.version' < package.json
"0.11.0"

❯ git rev-parse @
d4e283727876e4c1107256bee24b8135233a0494
```

```
❯ ./node_modules/.bin/mocha --reporter dot test

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  218 passing (7s)
  2 pending
  4 failing

  1) character encoding test A with decode = false does not decode:

      Uncaught AssertionError: expected 'ascii' to equal 'windows-1252'
      + expected - actual

      -ascii
      +windows-1252

      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at test/decoder_spec.js:23:53
      at done (lib/needle.js:377:14)
      at PassThrough.<anonymous> (lib/needle.js:576:9)
      at endReadableNT (_stream_readable.js:905:12)

  2) character encoding test A with decode = true decodes:

      Uncaught AssertionError: expected -1 not to equal -1 (false negative fail)
      + expected - actual


      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:174:17)
      at test/decoder_spec.js:39:50
      at done (lib/needle.js:377:14)
      at PassThrough.<anonymous> (lib/needle.js:576:9)
      at endReadableNT (_stream_readable.js:905:12)

  3) errors when host does not exist without callback emits end event once, with error:

      Uncaught AssertionError: expected 0 to be 1
      + expected - actual

      -0
      +1

      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at null._onTimeout (test/errors_spec.js:84:28)

  4) errors when host does not exist without callback error should be ENOTFOUND or EADDRINFO:
     Uncaught TypeError: Cannot read property 'code' of undefined
      at null._onTimeout (test/errors_spec.js:98:20)

```

**Comment by tomas** [comment]
I'm aware of the errors regarding the encoding tests, but the other ones I hadn't seen before. Which version of Node.js are you running?

**Comment by tomas** [comment]
This should be fixed now.
