### ISSUE TITLE
Disabling parse_response with defaults doesn't work

### ISSUE THREAD

**Issue by knksmith57** [tomas/needle#169]
Per [the example on the README.md](https://github.com/tomas/needle/blob/master/README.md#overriding-defaults), setting `parse_response` to false using `.defaults()` doesn't actually work:

```
needle.defaults({ parse_response: false });
```

Here's a diff of the test case I created to test:
```
❯ git diff
diff --git a/test/parsing_spec.js b/test/parsing_spec.js
index 3439a21..902207b 100644
--- a/test/parsing_spec.js
+++ b/test/parsing_spec.js
@@ -111,6 +111,12 @@ describe('parsing', function(){
     })

     describe('and parse option is false', function() {
+      var extend = require('util')._extend
+      var defaults = extend({}, needle.defaults())
+
+      beforeEach(function() {
+        needle.defaults(extend({}, defaults))
+      })

       it('does NOT return object', function(done){
         needle.get('localhost:' + port, { parse: false }, function(err, response, body) {
@@ -121,6 +127,18 @@ describe('parsing', function(){
         })
       })

+      it('does NOT return object when disabled using .defaults', function(done){
+        needle.defaults({
+          parse_response: false
+        })
+        needle.get('localhost:' + port, function(err, response, body) {
+          should.not.exist(err);
+          body.should.be.an.instanceof(Buffer)
+          body.toString().should.eql('{"foo":"bar"}');
+          done();
+        })
+      })
+
       it('should NOT have a .parser = json property', function(done) {
         needle.get('localhost:' + port, { parse: false }, function(err, resp) {
           should.not.exist(err);
```

And the results (trimmed to exclude errors already reported in #168):
```
❯ ./node_modules/.bin/mocha --reporter dot test

// ... pruned...

  5) parsing when response is an JSON string and parse option is false does NOT return object when disabled using .defaults:
     Uncaught AssertionError: expected Object { foo: 'bar' } to be an instance of Buffer
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at test/parsing_spec.js:136:39
      at done (lib/needle.js:377:14)
      at PassThrough.<anonymous> (lib/needle.js:576:9)
      at endReadableNT (_stream_readable.js:905:12)

```

**Comment by tomas** [comment]
Oh rats, I'll take a look at this right away.
