### ISSUE TITLE
Header content contains invalid character

### ISSUE THREAD

**Issue by afm-sayem** [tomas/needle#171]
I'm using `node-osmosis`(which uses needle) to scrape some data from a few local Bengali websites. While scraping through one of the sites, the scraper crashes with:
```
(get) [redirect] https://www.dailyjanakantha.com/details/article/185818/বাঁধ-ভেঙ্গে-পানির-নিচে-বোরো -> https://www.dailyjanakantha.com/details/article/185818/à¦¬à¦¾à¦à¦§-à¦­à§à¦à§à¦à§-à¦ªà¦¾à¦¨à¦¿à¦°-à¦¨à¦¿à¦à§-à¦¬à§à¦°à§
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:197:15)
    at Needle.send_request (/Users/USER/projects/chakrav/node_modules/needle/lib/needle.js:403:26)
    at ClientRequest.<anonymous> (/Users/USER/projects/chakrav/node_modules/needle/lib/needle.js:439:21)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:425:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
```

The url that I'm requesting is https://www.dailyjanakantha.com/details/article/185869/বাফুফে-নির্বাচনে-গরম-হাওয়া which redirects to https://www.dailyjanakantha.com/details/article/185869/à¦¬à¦¾à¦«à§à¦«à§-à¦¨à¦¿à¦°à§à¦¬à¦¾à¦à¦¨à§-à¦à¦°à¦®-à¦¹à¦¾à¦à§à¦¾

According to https://github.com/indexzero/http-server/issues/244 and https://github.com/akras14/validate-http-headers some of the characters in the URL are not valid. Any idea how to solve this?

**Comment by afm-sayem** [comment]
FYI, the way I'm working with it right now is by encoding the url in `send_request`.
```Javascript
Needle.prototype.send_request = function(count, method, uri, config, post_data, out, callback) {
  var uri = encodeURI(uri);
```

**Comment by tomas** [comment]
Interesting. So that trick fixes the problem?

**Comment by afm-sayem** [comment]
Yes. So far I haven't had any issues.

**Comment by tomas** [comment]
Would you care submitting a PR with your fix and a simple test case?

**Comment by afm-sayem** [comment]
Sure
