### ISSUE TITLE
EventEmitter memory leak with `connect`

### ISSUE THREAD

**Issue by SneakyMax** [tomas/needle#238]
This is like #161, but it's happening for me on the `connect` event:

```
(node:16251) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:223:19)
    at Socket.addListener (events.js:240:10)
    at Socket.Readable.on (_stream_readable.js:775:35)
    at Socket.once (events.js:271:8)
    at ClientRequest.<anonymous> (/home/etc/node_modules/needle/lib/needle.js:700:12)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:164:20)
    at tickOnSocket (_http_client.js:656:7)
    at onSocketNT (_http_client.js:672:5)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

*  Once a minute I'm sending off 4 HTTP requests to the same host
*  They aren't erroring or anything, including connect timeouts
*  In my last test it took 12 minutes to happen, but it's inconsistent
*  Node 9.3.0 and 8.9.4

I realize it might not be needle... going to try `request` to see if it happens there.

Basically the code I'm using (doesn't work as-is):

```javascript
setInterval( () => {
    const send = async () => {
        const response = await needle( 'PUT', url, body, {
            json: true,
            headers
        });
        if ( response.statusCode !== 200 )
            throw new Error( 'etc' );
    };

    const sends = [ send, send, send, send ];
    await promiseAll( sends, { concurrency: 5 }); // p-all package
}, 60 * 1000 );
```

**Comment by tomas** [comment]
Hey @SneakyMax. How did the other test go? Are you running the latest version of needle?

**Comment by SneakyMax** [comment]
@tomas no warnings with `request`. One error of `socket hang up` (but that's on our side, it could be the same thing that caused needle's warnings I suppose).

Was using needle 2.2.0.

**Comment by tomas** [comment]
What was/is causing the `socket hang up` error on your side? I'd love to replicate the issue over here.

**Comment by SneakyMax** [comment]
Honestly, no clue :(. It's a problem I've ran into a couple times with node
when making lots of http requests at once and haven't figured out the
cause.

**Comment by lucasexe** [comment]
the same error happened with me.
I removed it changing some lines:

```
request.once('socket', function(socket) {
    socket.once('connect', function() {
      set_timeout('response', config.response_timeout);
    });
```
to: 
```
request.once('socket', function(socket) {
    if(socket.connecting){
      socket.once('connect', function() {
        set_timeout('response', config.response_timeout);
      });
    } else {
      set_timeout('response', config.response_timeout);
    }
```

**Comment by tomas** [comment]
@lucasexe Good catch! I'll patch the code if it works.

**Comment by SneakyMax** [comment]
Thanks @lucasexe!
