### ISSUE TITLE
trows an error on server 

### ISSUE THREAD

**Issue by pahanishe** [tomas/needle#255]
i run this code on server (UBUNTU)
i can do curl 'https://www.google.com/'  from that server no problem, but the proxy trows an error for some reason socket hangs up... please help

**here is my code:**
      let url = 'https://www.google.com/';
      needle.get(url, function(error, response) {
        if (!error && response.statusCode == 200){
          res(response.body).header('Content-Type', response.headers['content-type']);
        }else{
          console.log("error", url, error);
          res("url was'nt found");
        }
      });

**and the error:**

 https://www.google.com/ { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:554:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }

**Comment by pahanishe** [comment]
ok i guess  i moved over to just making up my own little plugin for that, closing this one
